### ISSUE TITLE
make -jN run 

### ISSUE THREAD

**Issue by sharinoz** [chipsalliance/rocket-chip#1452]
hi all,
i try to make the Verilator emulator work, and according to the readme I need to run the following lines:
$ cd $ROCKETCHIP/emulator
$ make -jN run

but every time I try to run the second line I get this message:
make: *** No rule to make target '/home/rotemshahar/rocket/rocket-chip/riscv-tools//riscv64-unknown-elf/share/riscv-tests/isa/rv64um-v-mul', needed by 'output/rv64um-v-mul'.  Stop.

I tried with N=1 and N=2, I have tried a "clean" install of the riscv-gnu-toolchain outside thr rocket-chip directory, nothing worked for me.
I am using the gnu-toolchain and not the riscv-tools because the latter isn't working for me
I use ubuntu 16.04 64bit

thanks in advance

**Comment by michaeljclark** [comment]
> On 28/05/2018, at 2:26 AM, sharinoz <notifications@github.com> wrote:
> 
> hi all,
> i try to make the Verilator emulator work, and according to the readme I need to run the following lines:
> $ cd $ROCKETCHIP/emulator
> $ make -jN run
> 
> but every time I try to run the second line I get this message:
> make: *** No rule to make target '/home/rotemshahar/rocket/rocket-chip/riscv-tools//riscv64-unknown-elf/share/riscv-tests/isa/rv64um-v-mul', needed by 'output/rv64um-v-mul'. Stop.
> 
> I tried with N=1 and N=2, I have tried a "clean" install of the riscv-gnu-toolchain outside thr rocket-chip directory, nothing worked for me.
> I am using the gnu-toolchain and not the riscv-tools because the latter isn't working for me
> I use ubuntu 16.04 64bit
> 
> thanks in advance
> 
The error you are getting is because riscv-tests inside of the riscv-tools submodule has not been built.

You need to use the riscv-tools version included as a submodule of rocket-chip and this includes riscv-tests, riscv-gnu-toolchain along with various other build and test dependencies.

Note this text from the README

“The riscv-tools repository is already included in rocket-chip as a Git submodule. You must build this version of riscv-tools. For more information (or if you run into any issues), please consult the riscv-tools/README“
