### ISSUE TITLE
pos/count of RAS has no reset value, leading to cpu hang

### ISSUE THREAD

**Issue by kevin0823** [chipsalliance/rocket-chip#2121]
**Type of issue**: bug report | feature request | other enhancement

**Impact**: no functional change | API addition (no impact on existing code) | API modification | unknown

**Development Phase**: request | proposal

**Other information**
 

**If the current behavior is a bug, please provide the steps to reproduce the problem:**

**What is the current behavior?**

**What is the expected behavior?**

**Please tell us about your environment:**

**What is the use case for changing the behavior?**
rocket doesn't reset pos and count of RAS to zero, which makes the 'empty' wrong
For example, we assume that the value of count is 3 after reset, then we perform one fuction call in BOOTROM, and one load instruction is performed in this fuction. When we perform a ret instruction to return back, this ret might be replayed because the load is dcache missed. Once ret is replayed, RAS will be wrongly poped twice, and an invalid value will be returned because the count is not zero now. The wrong value may point to DDR, and the frontend will prefetch the instruction from this address. If we have not run the DDR initial code, the request send by frontend will hang cause the DDR have not ready.
Is this a bug in rocket?

**Comment by aswaterman** [comment]
Speculative fetch to cacheable regions is allowed behavior.

Reset is actually a red herring.  Even if those structures were reset, the problem you've encountered could still occur: the RAS will eventually become corrupted (e.g. due to a deep call stack) and cause an errant fetch.

Ideally, your DRAM controller would be better behaved, and instead of hanging, it would respond with an error.  Technically, your DRAM controller's behavior is a violation of the AXI spec.  You can work around it by installing a shim that will respond with errors prior to DRAM bringup, then after bringup, you can disable the shim.
