### ISSUE TITLE
rocket can not run

### ISSUE THREAD

**Issue by whutmsy** [chipsalliance/rocket-chip#2707]
i want make rocket into fpga accelerator. i use rocket-chip, testchipip and zynqadapter. when i simulate on vivado, the signal of rocket core is X. it has clock and reset. Why my rocket can not running.

**Comment by sequencer** [comment]
Would you mind providing more information? From currently information, we cannot debug with only one line problem description.

**Comment by whutmsy** [comment]
@sequencer thanks ! I package the rocket as a vitis rtl kernel. so i make the rocket only has a axi4 port. this port is the serial IO from testchipip. and i use the zynqadapter change the serial io to axi4 port. This is almost from fpga-zynq(https://github.com/ucb-bar/fpga-zynq). so my top module is only one axi4 port including clock and reset.

this is the tile waveform
![tile](https://user-images.githubusercontent.com/39824017/98326392-1b15de80-202c-11eb-838b-2ea8a89ece02.PNG)
this is the core waveform. 
![core](https://user-images.githubusercontent.com/39824017/98326397-1ea96580-202c-11eb-85a6-7232ab43fa0e.PNG)

**Comment by sequencer** [comment]
We mostly use diplomacy as uncore SoC generator, you drive your AXI with Xilinx part. You may need to take a look at your adapter part. And Vivado simulator or modelsim is also unsupported. So I think this is not a bug in rocket-chip.

My suggestion is take a look at fpga-shells rather than rocket-zynq. And use diplomacy to construct your desired SoC, rather than Xilinx bus IP.

**Comment by whutmsy** [comment]
@sequencer  thanks for your suggestion. The AXI4 port is used to write program into 0x80000000, and interrupt the rocket to run. i checked the data is rigth. when the rocket start to boot, I wonder if the rocket-chip run only need a clock, or any other signals.

**Comment by sequencer** [comment]
You also need reset.

**Comment by whutmsy** [comment]
@sequencer   thank you!

**Comment by sequencer** [comment]
Is this problem resolved?

**Comment by whutmsy** [comment]
@sequencer not yet. I am checking my waveform.  I have reset and clock signal. And the reset is from 1 to 0.  why the rocket can not boot. i give the bootrom, and 0x10040 is the beginning of bootrom. But the signal is X.

**Comment by whutmsy** [comment]
this is the tile .
![tile](https://user-images.githubusercontent.com/39824017/98334029-efe7bb00-203c-11eb-8558-c107c2f72495.PNG)

**Comment by sequencer** [comment]
Since there is no enough information about your environments and Xilinx Bus IP, I'm not able to help you on this.
You can take a look and try to understand verilator based simulation codes in
https://github.com/chipsalliance/rocket-chip/blob/master/vsim/Makefrag
And port to another simulator and bus interfaces.

**Comment by whutmsy** [comment]
@sequencer  I migth ignore some module. I use the chipyard verilator simulator using rocketconfig (https://github.com/ucb-bar/chipyard/blob/master/generators/chipyard/src/main/scala/config/RocketConfigs.scala), and i got right result.  I take out the processor and give clock and reset signal, finally got the same result as my previous simulation.

This is the top module.
![Top](https://user-images.githubusercontent.com/39824017/98436256-eb8ed100-2114-11eb-844f-c8d20a337e2c.PNG)

**Comment by whutmsy** [comment]
this is my Top module
![mytop](https://user-images.githubusercontent.com/39824017/98436504-b3888d80-2116-11eb-8e83-160a632fff3b.PNG)

**Comment by sequencer** [comment]
Sorry, I think I’m unable to help you on this, since the problem of you question is out of the rocket-chip.
My suggestion is you need to understand the simulation interface(by understanding verilator simulation(supported by rocket-chip) firstly) and adapter of Xilinx bus IP, before your own try on other simulation tool and IPs.
If you have any other question on codes related to rocket-chip, we may help you on this.
